/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * PolicyReportSummary provides a summary of results
 *
 * @export
 */
export interface PolicyReportSummary {
  /** error
   * Error provides the count of policies that could not be evaluated
   *
   * @required {false}
   * @format {int64}
   * @originalType {integer}
   */
  error?: number;
  /** fail
   * Fail provides the count of policies whose requirements were not met
   *
   * @required {false}
   * @format {int64}
   * @originalType {integer}
   */
  fail?: number;
  /** pass
   * Pass provides the count of policies whose requirements were met
   *
   * @required {false}
   * @format {int64}
   * @originalType {integer}
   */
  pass?: number;
  /** skip
   * Skip indicates the count of policies that were not selected for evaluation
   *
   * @required {false}
   * @format {int64}
   * @originalType {integer}
   */
  skip?: number;
  /** warn
   * Warn provides the count of non-scored policies whose requirements were not met
   *
   * @required {false}
   * @format {int64}
   * @originalType {integer}
   */
  warn?: number;
}
