/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * Timestamp indicates the time the result was found
 *
 * @export
 */
export interface PolicyReportResultsTimestamp {
  /** nanos
   * Non-negative fractions of a second at nanosecond resolution. Negative
second values with fractions must still have non-negative nanos values
that count forward in time. Must be from 0 to 999,999,999
inclusive. This field may be limited in precision depending on context.
   *
   * @required {true}
   * @format {int32}
   * @originalType {integer}
   */
  nanos: number;
  /** seconds
   * Represents seconds of UTC time since Unix epoch
1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
9999-12-31T23:59:59Z inclusive.
   *
   * @required {true}
   * @format {int64}
   * @originalType {integer}
   */
  seconds: number;
}
